# FYI - The following ODL env vars are passed and available from UOSCI:
#   AMULET_ODL_LOCATION
#   AMULET_ODL_HE_LOCATION
#   AMULET_ODL_LI_LOCATION
#   AMULET_ODL_BE_LOCATION
odl-controller:
  install-url: {{ env['AMULET_ODL_BE_LOCATION'] }}
  http-proxy: {{ env['AMULET_HTTP_PROXY'] }}
  https-proxy: {{ env['AMULET_HTTP_PROXY'] }}
